language: node_js

node_js: "node"

cache:
  directories:
    - "node_modules"

services:
  - mongodb

before_install:
  - npm i -g npm

install:
  - npm install

script: 
  - npm run build:code
  - npm run build:test:unit
  - npm run build:test:integration
  - npm run lint
  