language: node_js

node_js: "node"

cache:
  directories:
    - "node_modules"

services:
  - mongodb

before_install:
  - npm i -g npm

install:
  - npm install

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage Build
    - script: npm run build:code
    - stage Tests
    - script: npm run coverage